"""
Django settings for ReuPlan_Django project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if __name__ == "__main__":
    import sys

    from django.core.management import execute_from_command_line

    # Use 0.0.0.0 to bind to all available network interfaces
    # This allows connections from other devices in the same network
    sys.argv.append("0.0.0.0:8000")

    execute_from_command_line(sys.argv)




# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS =['.reuplan.lol','.reuplan.up.railway.app',"127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'coreapi',
    'corsheaders',
    'api',
]

AUTH_USER_MODEL = 'api.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ReuPlan_Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('frontend','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ReuPlan_Django.wsgi.application'

DATABASES = {'default':dj_database_url.config(default=os.getenv('DATABASE_URL'))}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

imported_cors_from_env = os.getenv("CORS_ORIGINS")
parsed_cors_from_env = [origin.strip() for origin in imported_cors_from_env.split(',') if origin.strip()]

if os.getenv("WORKING_MODE") == "development":
    print("DEVELOPMENT MODE ON")
    CORS_ALLOW_ALL_ORIGINS = True
else:
    print("PRODUCTION MODE ON")
    CORS_ALLOWED_ORIGINS = parsed_cors_from_env

CORS_ALLOWED_ORIGINS = parsed_cors_from_env

CORS_ALLOW_HEADERS = [
    'content-type',
    'x-csrftoken',
    "Authorization"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',
        'user': '500/hour'
    }

}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST ='smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None    

if os.getenv("WORKING_MODE") == "development":

    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SECURE = False
    # CSRF_COOKIE_DOMAIN = '127.0.0.1'
else:
    CSRF_COOKIE_SAMESITE = 'Strict'
    SESSION_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True

CORS_ALLOW_CREDENTIALS = True


#For PRODUCTION BOTH TRUE
# CSRF_COOKIE_HTTPONLY = True
# SESSION_COOKIE_HTTPONLY = True
#CSRF_COOKIE_SECURE = True

#FOR DEV
# CSRF_COOKIE_HTTPONLY = False
# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_SECURE = False

STATICFILES_DIRS = [BASE_DIR.joinpath('frontend','dist','assets')]
STATIC_ROOT = BASE_DIR.joinpath('staticfiles')

CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000/","http://127.0.0.1:5173","http://localhost:5173","https://reuplan.up.railway.app","https://www.reuplan.lol","https://reuplan.lol","http://192.168.1.11:5173"]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

